[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun" 

[rpc_endpoints]
private = "${PRIVATE_KEY}"
sepolia = "${SEPOLIA_URL}"
mainnet = "${MAINNET_URL}"
[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
